spring.application.name=motolocation
server.port=8080

# PostgreSQL Docker Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/motolocation
spring.datasource.username=mottu
spring.datasource.password=mottu_password

# Enable Flyway
spring.flyway.enabled=true

# Set Hibernate to validate what Flyway creates
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true