    -- Criando a tabela MOTO
    CREATE TABLE MOTO (
        ID NUMBER(19,0) NOT NULL,
        PLACA VARCHAR2(255) NOT NULL,
        MODELO VARCHAR2(255) NOT NULL,
        ANO NUMBER(10,0) NOT NULL,
        RFID_TAG VARCHAR2(255) NOT NULL,
        STATUS VARCHAR2(255),
        OBSERVACOES VARCHAR2(255),
        CONSTRAINT PK_MOTO PRIMARY KEY (ID),
        CONSTRAINT UK_MOTO_PLACA UNIQUE (PLACA),
        CONSTRAINT UK_MOTO_RFID_TAG UNIQUE (RFID_TAG)
    );
    CREATE SEQUENCE MOTO_SEQ START WITH 1 INCREMENT BY 1;

    -- Criando a tabela USERS
    CREATE TABLE USERS (
        ID NUMBER(19,0) NOT NULL,
        USERNAME VARCHAR2(255) NOT NULL,
        PASSWORD VARCHAR2(255) NOT NULL,
        ROLE VARCHAR2(255) NOT NULL,
        CONSTRAINT PK_USERS PRIMARY KEY (ID),
        CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME)
    );
    CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;

    -- Criando a tabela SENSOR
    CREATE TABLE SENSOR (
        ID NUMBER(19,0) NOT NULL,
        CODIGO VARCHAR2(255) NOT NULL,
        POSICAO_X NUMBER(10,0) NOT NULL,
        POSICAO_Y NUMBER(10,0) NOT NULL,
        DESCRICAO VARCHAR2(255),
        CONSTRAINT PK_SENSOR PRIMARY KEY (ID),
        CONSTRAINT UK_SENSOR_CODIGO UNIQUE (CODIGO)
    );
    CREATE SEQUENCE SENSOR_SEQ START WITH 1 INCREMENT BY 1;

    -- Criando a tabela MOVIMENTACAO
    CREATE TABLE MOVIMENTACAO (
        ID NUMBER(19,0) NOT NULL,
        MOTO_ID NUMBER(19,0) NOT NULL,
        SENSOR_ID NUMBER(19,0) NOT NULL,
        DATA_HORA TIMESTAMP,
        CONSTRAINT PK_MOVIMENTACAO PRIMARY KEY (ID),
        CONSTRAINT FK_MOVIMENTACAO_MOTO FOREIGN KEY (MOTO_ID) REFERENCES MOTO(ID),
        CONSTRAINT FK_MOVIMENTACAO_SENSOR FOREIGN KEY (SENSOR_ID) REFERENCES SENSOR(ID)
    );
    CREATE SEQUENCE MOVIMENTACAO_SEQ START WITH 1 INCREMENT BY 1;

    -- Inserindo usuários iniciais
    INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE)
    VALUES (USERS_SEQ.nextval, 'admin', '$2a$10$fP22bQy7sT41iM54G.3v4.P.9w/Yj.HM.g/9.3.T.tgl9e.e/zY.K', 'ROLE_ADMIN');

    INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE)
    VALUES (USERS_SEQ.nextval, 'user', '$2a$10$b7b.s.G.q.p1y.qg.01h.uX.Vb.5u.1b.i2t.f.h.a.5c.f.i.s.s', 'ROLE_USER');