CREATE TABLE MOTO (
    ID NUMBER(19,0) NOT NULL,
    PLACA VARCHAR2(255) NOT NULL,
    MODELO VARCHAR2(255) NOT NULL,
    ANO NUMBER(10,0) NOT NULL,
    RFID_TAG VARCHAR2(255) NOT NULL,
    STATUS VARCHAR2(255),
    OBSERVACOES VARCHAR2(255),
    CONSTRAINT PK_MOTO PRIMARY KEY (ID),
    CONSTRAINT UK_MOTO_PLACA UNIQUE (PLACA),
    CONSTRAINT UK_MOTO_RFID_TAG UNIQUE (RFID_TAG)
);
CREATE SEQUENCE MOTO_SEQ START WITH 1 INCREMENT BY 1;