CREATE TABLE MOTO (
    ID BIGSERIAL PRIMARY KEY,
    PLACA VARCHAR(255) NOT NULL UNIQUE,
    MODELO VARCHAR(255) NOT NULL,
    ANO INT NOT NULL,
    RFID_TAG VARCHAR(255) NOT NULL UNIQUE,
    STATUS VARCHAR(255),
    OBSERVACOES VARCHAR(255)
);