CREATE TABLE SENSOR (
    ID NUMBER(19,0) NOT NULL,
    CODIGO VARCHAR2(255) NOT NULL,
    POSICAO_X NUMBER(10,0) NOT NULL,
    POSICAO_Y NUMBER(10,0) NOT NULL,
    DESCRICAO VARCHAR2(255),
    CONSTRAINT PK_SENSOR PRIMARY KEY (ID),
    CONSTRAINT UK_SENSOR_CODIGO UNIQUE (CODIGO)
);
CREATE SEQUENCE SENSOR_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE MOVIMENTACAO (
    ID NUMBER(19,0) NOT NULL,
    MOTO_ID NUMBER(19,0) NOT NULL,
    SENSOR_ID NUMBER(19,0) NOT NULL,
    DATA_HORA TIMESTAMP,
    CONSTRAINT PK_MOVIMENTACAO PRIMARY KEY (ID),
    CONSTRAINT FK_MOVIMENTACAO_MOTO FOREIGN KEY (MOTO_ID) REFERENCES MOTO(ID),
    CONSTRAINT FK_MOVIMENTACAO_SENSOR FOREIGN KEY (SENSOR_ID) REFERENCES SENSOR(ID)
);
CREATE SEQUENCE MOVIMENTACAO_SEQ START WITH 1 INCREMENT BY 1;