CREATE TABLE SENSOR (
    ID BIGSERIAL PRIMARY KEY,
    CODIGO VARCHAR(255) NOT NULL UNIQUE,
    posicao_x INT NOT NULL, -- Corrigido
    posicao_y INT NOT NULL, -- Corrigido
    DESCRICAO VARCHAR(255)
);

CREATE TABLE MOVIMENTACAO (
    ID BIGSERIAL PRIMARY KEY,
    MOTO_ID BIGINT NOT NULL,
    SENSOR_ID BIGINT NOT NULL,
    DATA_HORA TIMESTAMP,
    CONSTRAINT FK_MOVIMENTACAO_MOTO FOREIGN KEY (MOTO_ID) REFERENCES MOTO(ID),
    CONSTRAINT FK_MOVIMENTACAO_SENSOR FOREIGN KEY (SENSOR_ID) REFERENCES SENSOR(ID)
);