CREATE TABLE USERS (
    ID NUMBER(19,0) NOT NULL,
    USERNAME VARCHAR2(255) NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (ID),
    CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME)
);
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;